name: google_language_fonts
description: Include easily Google Fonts which are compatible with your languages.
version: 3.0.0
repository: https://github.com/mzdm/google-language-fonts-flutter

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  path_provider: ^2.0.15
  crypto: ^3.0.3
  meta: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1
  mockito: ^5.4.0
  mustache_template: ^2.0.0
  protobuf: ^2.1.0
  build_runner: ^2.3.3
  protoc_plugin: ^20.0.1
  console: ^4.1.0
